# Generated by Django 5.2.4 on 2025-08-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
